name: Run Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Ensure write permissions for docs folder
        run: chmod -R 777 docs

      - name: List directory contents
        run: ls -l
      
      - name: Run Python script to generate HTML
        run: python scripts/main.py

      - name: List directory contents after script execution
        run: ls -l
