name: Run Dash App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to generate HTML
        run: python scripts/main.py

      - name: Upload HTML file
        uses: actions/upload-artifact@v2
        with:
          name: web-page
          path: web/index.html
