name: Update index.html

on:
  schedule:
    - cron: '0 19 * * *'  # Runs at 7:00 PM UTC every day (this is Brasilia 4:00 pm)
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run the script
      run: |
        python scripts/main.py  

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/index.html
        git commit -m 'Update index.html via GitHub Actions'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
